version: 2

models:

  - name: stg_transactions
    description: transactions table stage
    config:
      materialized: view
 

  - name: ft_customer_transactions
    description: transactions by customer
    config:
      materialized: table

  - name: ft_transaction_times
    description: transaction timing features
    config:
      materialized: table
      tags: ['python']
